version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306 

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/hotel_db
    volumes:
      - .:/app
      - .docker/wait-for-db.sh:/app/wait-for-db.sh  # Add this line to mount the script
    ports:
      - 3000:3000
    command: sh -c "/app/wait-for-db.sh db 3306 && npm install && npm run prisma:migrate && npm run prisma:seed && npm test && npm run dev"

volumes:
  mysql-data:
